export const genres = [
  {
    id: 28,
    name: 'Action',
  },
  {
    id: 12,
    name: 'Adventure',
  },
  {
    id: 16,
    name: 'Animation',
  },
  {
    id: 35,
    name: 'Comedy',
  },
  {
    id: 80,
    name: 'Crime',
  },
  {
    id: 99,
    name: 'Documentary',
  },
  {
    id: 18,
    name: 'Drama',
  },
  {
    id: 10751,
    name: 'Family',
  },
  {
    id: 14,
    name: 'Fantasy',
  },
  {
    id: 36,
    name: 'History',
  },
  {
    id: 27,
    name: 'Horror',
  },
  {
    id: 10402,
    name: 'Music',
  },
  {
    id: 9648,
    name: 'Mystery',
  },
  {
    id: 10749,
    name: 'Romance',
  },
  {
    id: 878,
    name: 'Science Fiction',
  },
  {
    id: 10770,
    name: 'TV Movie',
  },
  {
    id: 53,
    name: 'Thriller',
  },
  {
    id: 10752,
    name: 'War',
  },
  {
    id: 37,
    name: 'Western',
  },
]

export const movies = [
  {
    adult: false,
    backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
    genre_ids: [28, 12, 878],
    id: 505642,
    original_language: 'en',
    original_title: 'Black Panther: Wakanda Forever',
    overview:
      'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
    popularity: 7332.994,
    poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
    release_date: '2022-11-09',
    title: 'Black Panther: Wakanda Forever',
    video: false,
    vote_average: 7.5,
    vote_count: 2763,
  },
  {
    adult: false,
    backdrop_path: '/tGwO4xcBjhXC0p5qlkw37TrH6S6.jpg',
    genre_ids: [16, 12, 35, 10751, 14],
    id: 315162,
    original_language: 'en',
    original_title: 'Puss in Boots: The Last Wish',
    overview:
      'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
    popularity: 3332.879,
    poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
    release_date: '2022-12-07',
    title: 'Puss in Boots: The Last Wish',
    video: false,
    vote_average: 8.6,
    vote_count: 3438,
  },
  {
    adult: false,
    backdrop_path: '/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg',
    genre_ids: [28, 10749, 35],
    id: 758009,
    original_language: 'en',
    original_title: 'Shotgun Wedding',
    overview:
      'Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.',
    popularity: 3262.822,
    poster_path: '/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg',
    release_date: '2022-12-28',
    title: 'Shotgun Wedding',
    video: false,
    vote_average: 6.3,
    vote_count: 303,
  },
  {
    adult: false,
    backdrop_path: '/a4I481szRmycyreQTLrRe4f4YJe.jpg',
    genre_ids: [80, 53, 18],
    id: 842544,
    original_language: 'en',
    original_title: 'Transfusion',
    overview:
      'Ryan Logan, a former Special Forces operative, is battling to cope with life after the loss of his wife.  He is thrusted into the criminal underworld to keep his only son from being taken from him.',
    popularity: 2029.48,
    poster_path: '/bxh5xCCW9Ynfg6EZJWUkc1zqTnr.jpg',
    release_date: '2023-01-05',
    title: 'Transfusion',
    video: false,
    vote_average: 6.5,
    vote_count: 44,
  },
  {
    adult: false,
    backdrop_path: '/tCpMRsHlfR6CcqJYA3kJMS3YApt.jpg',
    genre_ids: [28, 53, 80],
    id: 1035806,
    original_language: 'en',
    original_title: 'Detective Knight: Independence',
    overview:
      "Detective James Knight 's last-minute assignment to the Independence Day shift turns into a race to stop an unbalanced ambulance EMT from imperiling the city's festivities. The misguided vigilante, playing cop with a stolen gun and uniform, has a bank vault full of reasons to put on his own fireworks show... one that will strike dangerously close to Knight's home.",
    popularity: 1939.142,
    poster_path: '/jrPKVQGjc3YZXm07OYMriIB47HM.jpg',
    release_date: '2023-01-20',
    title: 'Detective Knight: Independence',
    video: false,
    vote_average: 6.8,
    vote_count: 32,
  },
  {
    adult: false,
    backdrop_path: '/q2fY4kMXKoGv4CQf310MCxpXlRI.jpg',
    genre_ids: [878, 27, 35],
    id: 536554,
    original_language: 'en',
    original_title: 'M3GAN',
    overview:
      "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
    popularity: 1967.69,
    poster_path: '/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg',
    release_date: '2022-12-28',
    title: 'M3GAN',
    video: false,
    vote_average: 7.6,
    vote_count: 1409,
  },
  {
    adult: false,
    backdrop_path: '/qHdPNd1cUaSNYLLNgt1Pv3LVd0T.jpg',
    genre_ids: [878, 28, 12],
    id: 843794,
    original_language: 'ko',
    original_title: '정이',
    overview:
      'On an uninhabitable 22nd-century Earth, the outcome of a civil war hinges on cloning the brain of an elite soldier to create a robot mercenary.',
    popularity: 1755.471,
    poster_path: '/z2nfRxZCGFgAnVhb9pZO87TyTX5.jpg',
    release_date: '2023-01-20',
    title: 'JUNG_E',
    video: false,
    vote_average: 6.4,
    vote_count: 254,
  },
  {
    adult: false,
    backdrop_path: '/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg',
    genre_ids: [28, 12, 53],
    id: 646389,
    original_language: 'en',
    original_title: 'Plane',
    overview:
      'After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.',
    popularity: 1628.131,
    poster_path: '/2g9ZBjUfF1X53EinykJqiBieUaO.jpg',
    release_date: '2023-01-13',
    title: 'Plane',
    video: false,
    vote_average: 6.8,
    vote_count: 206,
  },
  {
    adult: false,
    backdrop_path: '/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg',
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: 'en',
    original_title: 'Avatar: The Way of Water',
    overview:
      'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    popularity: 1418.818,
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    release_date: '2022-12-14',
    title: 'Avatar: The Way of Water',
    video: false,
    vote_average: 7.7,
    vote_count: 5137,
  },
  {
    adult: false,
    backdrop_path: '/f9PSbuMeBS5CuHEOVyymg5lcq8J.jpg',
    genre_ids: [28, 53, 9648, 80, 27],
    id: 996727,
    original_language: 'en',
    original_title: 'The Price We Pay',
    overview:
      'After a pawn shop robbery goes askew, two criminals take refuge at a remote farmhouse to try to let the heat die down, but find something much more menacing.',
    popularity: 1330.737,
    poster_path: '/8fwJt0qZieQ7dKaiiqehObWpXYT.jpg',
    release_date: '2023-01-13',
    title: 'The Price We Pay',
    video: false,
    vote_average: 6.4,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: '/cU7itLM8qmwMiaNnWsJPQLKe79j.jpg',
    genre_ids: [878, 27, 12, 28],
    id: 1013870,
    original_language: 'en',
    original_title: 'Kids vs. Aliens',
    overview:
      'All Gary wants is to make awesome home movies with his best buds. All his older sister Samantha wants is to hang with the cool kids. When their parents head out of town one Halloween weekend, an all-time rager of a teen house party turns to terror when aliens attack, forcing the siblings to band together to survive the night.',
    popularity: 1325.947,
    poster_path: '/wQ53sO5n9LCFbssV3oQ4CuajL1L.jpg',
    release_date: '2023-01-20',
    title: 'Kids vs. Aliens',
    video: false,
    vote_average: 5.6,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: '/5pMy5LF2JAleBNBtuzizfCMWM7k.jpg',
    genre_ids: [10752, 36, 18],
    id: 653851,
    original_language: 'en',
    original_title: 'Devotion',
    overview:
      "The harrowing true story of two elite US Navy fighter pilots during the Korean War. Their heroic sacrifices would ultimately make them the Navy's most celebrated wingmen.",
    popularity: 1354.401,
    poster_path: '/26yQPXymbWeCLKwcmyL8dRjAzth.jpg',
    release_date: '2022-11-23',
    title: 'Devotion',
    video: false,
    vote_average: 7.7,
    vote_count: 251,
  },
  {
    adult: false,
    backdrop_path: '/vLPSvAt1CnfmDCeqG3zkFh0s6S4.jpg',
    genre_ids: [10752, 28],
    id: 542196,
    original_language: 'en',
    original_title: 'Wolf Hound',
    overview:
      'Inspired by the real-life German special operations unit KG 200 that shot down, repaired, and flew Allied aircraft as Trojan horses, "Wolf Hound" takes place in 1944 German-occupied France and follows the daring exploits of Jewish-American fighter pilot Captain David Holden. Ambushed behind enemy lines, Holden must rescue a captured B-17 Flying Fortress crew, evade a ruthless enemy stalking him at every turn, and foil a plot that could completely alter the outcome of World War II.',
    popularity: 1120.764,
    poster_path: '/gHC0eFvXXNokP3sSNCTG2uks87R.jpg',
    release_date: '2022-06-03',
    title: 'Wolf Hound',
    video: false,
    vote_average: 7.4,
    vote_count: 42,
  },
  {
    adult: false,
    backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
    genre_ids: [14, 28, 878],
    id: 436270,
    original_language: 'en',
    original_title: 'Black Adam',
    overview:
      'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
    popularity: 979.683,
    poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
    release_date: '2022-10-19',
    title: 'Black Adam',
    video: false,
    vote_average: 7.2,
    vote_count: 4084,
  },
  {
    adult: false,
    backdrop_path: '/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg',
    genre_ids: [35, 80, 9648],
    id: 661374,
    original_language: 'en',
    original_title: 'Glass Onion: A Knives Out Mystery',
    overview:
      'World-famous detective Benoit Blanc heads to Greece to peel back the layers of a mystery surrounding a tech billionaire and his eclectic crew of friends.',
    popularity: 937.092,
    poster_path: '/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg',
    release_date: '2022-11-23',
    title: 'Glass Onion: A Knives Out Mystery',
    video: false,
    vote_average: 7.1,
    vote_count: 3355,
  },
  {
    adult: false,
    backdrop_path: '/Aqldsq65Nj1KAkQD2MzkZsAk5N5.jpg',
    genre_ids: [28, 53, 18],
    id: 846433,
    original_language: 'es',
    original_title: 'The Enforcer',
    overview:
      'A noir thriller set in Miami, the film follows an enforcer who discovers his femme fatale boss has branched out into cyber sex trafficking, putting a young runaway he’s befriended at risk. He sacrifices everything to save the young girl from the deadly organization he’s spent his life building.',
    popularity: 911.722,
    poster_path: '/pXC8JJbfnRWtbD8i2yKFqqWEO4X.jpg',
    release_date: '2022-09-22',
    title: 'The Enforcer',
    video: false,
    vote_average: 7.4,
    vote_count: 175,
  },
  {
    adult: false,
    backdrop_path: '/96SADhPnkXnVN3KaRKsDeBovLcm.jpg',
    genre_ids: [28, 14, 10770],
    id: 877703,
    original_language: 'en',
    original_title: 'Teen Wolf: The Movie',
    overview:
      'The wolves are howling once again, as a terrifying ancient evil emerges in Beacon Hills. Scott McCall, no longer a teenager yet still an Alpha, must gather new allies and reunite trusted friends to fight back against this powerful and deadly enemy.',
    popularity: 850.551,
    poster_path: '/wAkpPm3wcHRqZl8XjUI3Y2chYq2.jpg',
    release_date: '2023-01-18',
    title: 'Teen Wolf: The Movie',
    video: false,
    vote_average: 8.2,
    vote_count: 372,
  },
  {
    adult: false,
    backdrop_path: '/8oBSFGFaHp2MtTMeuWZ2ugmx28m.jpg',
    genre_ids: [18],
    id: 511617,
    original_language: 'ja',
    original_title: '伯林漂流',
    overview:
      'Kôichi is a Japanese man living alone in Berlin. He has no job and hardly any friends. One night Kôichi meets Ryota at a bar which is also a sex club. Ryota came to Berlin to visit a German guy whom he had "met" on a dating app. His high hopes for romance (and marriage?) were quickly crushed since the German was only interested in sex, not even letting Ryota stay for the night. That is why Ryota ended up spending the night in the dark room of the sex club. Kôichi for some reason lets Ryota stay at his apartment. They have sex. Ryota goes out almost everyday to get laid by various local men and comes home to Kôichi\'s. Increasingly caught up with a strange feeling that is akin to but not quite frustration or curiosity (needless to say, it is not even close to love), Kôichi gradually gives himself up to sex with Ryota.',
    popularity: 846.504,
    poster_path: '/aH0yHU915NibzznpB2Zks2c6Z9O.jpg',
    release_date: '2017-09-10',
    title: 'Berlin Drifters',
    video: false,
    vote_average: 5,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: '/sBOenwOZGRN5nZZGw4TxwtnfrEf.jpg',
    genre_ids: [28, 35, 80, 53],
    id: 899112,
    original_language: 'en',
    original_title: 'Violent Night',
    overview:
      'When a team of mercenaries breaks into a wealthy family compound on Christmas Eve, taking everyone inside hostage, the team isn’t prepared for a surprise combatant: Santa Claus is on the grounds, and he’s about to show why this Nick is no saint.',
    popularity: 806.129,
    poster_path: '/1XSYOP0JjjyMz1irihvWywro82r.jpg',
    release_date: '2022-11-30',
    title: 'Violent Night',
    video: false,
    vote_average: 7.6,
    vote_count: 1136,
  },
  {
    adult: false,
    backdrop_path: '/8oj1pbizI6RS5xlyETmlWh9mVqN.jpg',
    genre_ids: [27],
    id: 955991,
    original_language: 'en',
    original_title: 'The Offering',
    overview:
      'In the wake of a young Jewish girl’s disappearance, the son of a Hasidic funeral director returns home with his pregnant wife in hopes of reconciling with his father. Little do they know that directly beneath them in the family morgue, an ancient evil with sinister plans for the unborn child lurks inside a mysterious corpse.',
    popularity: 812.947,
    poster_path: '/tbaTFgGIaTL1Uhd0SMob6Dhi5cK.jpg',
    release_date: '2023-01-11',
    title: 'The Offering',
    video: false,
    vote_average: 5.7,
    vote_count: 43,
  },
]

export const tvShows = [
  {
    backdrop_path: '/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    first_air_date: '2023-01-15',
    genre_ids: [18, 10759],
    id: 100088,
    name: 'The Last of Us',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'The Last of Us',
    overview:
      'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.',
    popularity: 4048.077,
    poster_path: '/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    vote_average: 8.8,
    vote_count: 1525,
  },
  {
    backdrop_path: '/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg',
    first_air_date: '2021-08-03',
    genre_ids: [10766],
    id: 130542,
    name: 'Bhagya Lakshmi',
    origin_country: ['IN'],
    original_language: 'hi',
    original_name: 'Bhagya Lakshmi',
    overview:
      'Hailing from a middle-class family, Lakshmi’s life is upended when she realises that her marriage to Rishi Oberoi, an industrialist’s son, is a sham to keep his death at bay.',
    popularity: 1796.901,
    poster_path: '/7wuKrFvbX7kAIF0ctotARsqayPo.jpg',
    vote_average: 5.2,
    vote_count: 19,
  },
  {
    backdrop_path: '/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg',
    first_air_date: '2022-11-23',
    genre_ids: [10765, 9648, 35],
    id: 119051,
    name: 'Wednesday',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Wednesday',
    overview:
      'Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.',
    popularity: 1161.17,
    poster_path: '/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
    vote_average: 8.7,
    vote_count: 6299,
  },
  {
    backdrop_path: '/igmqMTV2Ukf5Id4WwQi7MUAJQAX.jpg',
    first_air_date: '2021-10-27',
    genre_ids: [18],
    id: 197109,
    name: 'Yeh Rishta Kya Kehlata Hai',
    origin_country: ['IN'],
    original_language: 'hi',
    original_name: 'ये रिश्ता क्या कहलाता है',
    overview:
      "A personal tragedy creates a rift in Abhimanyu and Akshara's marital life. Years later, when destiny offers a second chance, will the duo embrace love?",
    popularity: 1505.902,
    poster_path: '/6ZfiG4P7jivJV0wgcNMSiS2Owhh.jpg',
    vote_average: 4.4,
    vote_count: 9,
  },
  {
    backdrop_path: '/zxfBtHz5UmSTfIEC4O4GngyjHwa.jpg',
    first_air_date: '2023-01-15',
    genre_ids: [18, 10765],
    id: 204541,
    name: 'Three-Body',
    origin_country: ['CN'],
    original_language: 'zh',
    original_name: '三体',
    overview:
      "Nanotechnology researcher Wang Miao is taken to the Joint Operations Center by police officer Shi Qiang, who's investigating the mysterious suicide wave among scientists worldwide,  and recruited to sneak into an organization called the Frontiers of Science to help the investigation. When Wang Miao is contacted by the leader of the organization, Shen Yufei, she introduces him to a sophisticated VR video game called Three-Body, but soon he discovers that it's more than just a game.",
    popularity: 1483.651,
    poster_path: '/vvKuYw2vmaBbWNgNxEQkuYYpX2l.jpg',
    vote_average: 8.4,
    vote_count: 74,
  },
  {
    backdrop_path: '/2cvMMvo8VUfuQ40FYtIrqzoh7sG.jpg',
    first_air_date: '2013-04-15',
    genre_ids: [80, 18, 10766],
    id: 44953,
    name: 'The Lord of the Skies',
    origin_country: ['MX'],
    original_language: 'es',
    original_name: 'El señor de los cielos',
    overview:
      'Set in the 1990s, these are the life and times of Amado Carrillo Fuentes, a man who became the head of the Juárez cartel. Nicknamed “El Señor de los Cielos” (Lord of the Skies) because of the large fleet of airplanes he used to transport drugs, he was also known for washing more than $200 million through Colombia to finance his huge fleet. He is described as the most powerful drug trafficker of his time.',
    popularity: 1028.396,
    poster_path: '/Ag7VUdnrRz5Qpq3Yn3E5OCvFnu0.jpg',
    vote_average: 7.9,
    vote_count: 2367,
  },
  {
    backdrop_path: '/r8CYgYLotlG0kHwZT5V64Hacc5J.jpg',
    first_air_date: '2023-01-27',
    genre_ids: [80, 9648],
    id: 215333,
    name: 'The Snow Girl',
    origin_country: ['ES'],
    original_language: 'es',
    original_name: 'La chica de nieve',
    overview:
      "When a little girl goes missing during a parade in Málaga, a young newspaper journalist becomes fiercely determined to help Amaya's parents find her.",
    popularity: 979.353,
    poster_path: '/iPPFBfCxcxIHH6JdavjyOIXMj1O.jpg',
    vote_average: 7.3,
    vote_count: 63,
  },
  {
    backdrop_path: '/tLL91JBiCCvBF7oKSN6dFR7yd8c.jpg',
    first_air_date: '2021-12-20',
    genre_ids: [10764],
    id: 153870,
    name: 'Shark Tank India',
    origin_country: ['IN'],
    original_language: 'hi',
    original_name: 'Shark Tank India',
    overview:
      'Aspiring entrepreneurs from India pitch their business models to a panel of investors and persuade them to invest money in their idea.',
    popularity: 1421.466,
    poster_path: '/iGw6R4e4G07xjffVifFLSN3dEAb.jpg',
    vote_average: 7.2,
    vote_count: 9,
  },
  {
    backdrop_path: '/qcpC9lv6VLL4Zw45EveYELyje1w.jpg',
    first_air_date: '2020-10-05',
    genre_ids: [18, 10766, 10751],
    id: 111453,
    name: 'Gumm Hai Kisi Ke Pyaar Mein',
    origin_country: ['IN'],
    original_language: 'hi',
    original_name: 'घुम है किसिकी प्यार में',
    overview:
      'Virat sacrifices his love to honour the promise he made to a dying man. Trapped between the past and the present, will he find love beyond the chains of duty?',
    popularity: 1421.143,
    poster_path: '/uNjnoT3RChs2r7O9pDyx7TNBvIj.jpg',
    vote_average: 5.7,
    vote_count: 25,
  },
  {
    backdrop_path: '/mNHRGO1gFpR2CYZdANe72kcKq7G.jpg',
    first_air_date: '2022-11-13',
    genre_ids: [80, 18],
    id: 153312,
    name: 'Tulsa King',
    origin_country: ['US'],
    original_language: 'en',
    original_name: 'Tulsa King',
    overview:
      'Just after he is released from prison after 25 years, New York mafia capo Dwight “The General” Manfredi is unceremoniously exiled by his boss to set up shop in Tulsa, Okla. Realizing that his mob family may not have his best interests in mind, Dwight slowly builds a “crew” from a group of unlikely characters, to help him establish a new criminal empire in a place that to him might as well be another planet.',
    popularity: 1328.156,
    poster_path: '/fwTv3RPRAIy0maOMns5eYRRwnDk.jpg',
    vote_average: 8.5,
    vote_count: 785,
  },
  {
    backdrop_path: '/o8zk3QmHYMSC7UiJgFk81OFF1sc.jpg',
    first_air_date: '2022-08-22',
    genre_ids: [10766, 18],
    id: 204095,
    name: 'Mar do Sertão',
    origin_country: ['BR'],
    original_language: 'pt',
    original_name: 'Mar do Sertão',
    overview: '',
    popularity: 1402.428,
    poster_path: '/ixgnqO8xhFMb1zr8RRFsyeZ9CdD.jpg',
    vote_average: 4.3,
    vote_count: 21,
  },
  {
    backdrop_path: '/ymkFaEO0UdYXKIgcWZ23TlYIRD9.jpg',
    first_air_date: '2020-11-16',
    genre_ids: [18, 10766, 10751],
    id: 113218,
    name: 'Imlie',
    origin_country: ['IN'],
    original_language: 'hi',
    original_name: 'इमली',
    overview:
      "All Imlie wanted was to create a name for herself in the city. But upon her arrival, she finds herself caught in the middle of Aditya and Malini's love story.",
    popularity: 1351.482,
    poster_path: '/brajFHvqeitbp7ifevWpFpirS4S.jpg',
    vote_average: 5.1,
    vote_count: 7,
  },
  {
    backdrop_path: '/caGVr9Il2gj8bN4ow6qsLm60TxM.jpg',
    first_air_date: '2005-03-27',
    genre_ids: [18],
    id: 1416,
    name: "Grey's Anatomy",
    origin_country: ['US'],
    original_language: 'en',
    original_name: "Grey's Anatomy",
    overview:
      'Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.',
    popularity: 983.205,
    poster_path: '/daSFbrt8QCXV2hSwB0hqYjbj681.jpg',
    vote_average: 8.3,
    vote_count: 8912,
  },
  {
    backdrop_path: '/1aQ0ETcIXFeC0uGcK7NvTg90zWi.jpg',
    first_air_date: '2022-08-22',
    genre_ids: [10751, 10766],
    id: 209326,
    name: 'Rajjo',
    origin_country: ['IN'],
    original_language: 'hi',
    original_name: 'Rajjo',
    overview: '',
    popularity: 1285.309,
    poster_path: '/rdNwXdMDVDvjOlcXCPOR3m9t43r.jpg',
    vote_average: 5.1,
    vote_count: 5,
  },
  {
    backdrop_path: '/7EN05ntpEmpXgmSNCF1m0YfisVb.jpg',
    first_air_date: '2023-01-16',
    genre_ids: [10766, 35],
    id: 209117,
    name: 'Vai na Fé',
    origin_country: ['BR'],
    original_language: 'pt',
    original_name: 'Vai na Fé',
    overview: '',
    popularity: 1278.074,
    poster_path: '/zU0MgcYQuMvB4bAqcqi7gDcWQKm.jpg',
    vote_average: 6,
    vote_count: 2,
  },
  {
    backdrop_path: '/xYt0GHDtkeuDsPnrMT7lReWHi3T.jpg',
    first_air_date: '2009-03-30',
    genre_ids: [35, 18, 10766],
    id: 32209,
    name: 'Al Fondo Hay Sitio',
    origin_country: ['PE'],
    original_language: 'es',
    original_name: 'Al Fondo Hay Sitio',
    overview:
      "Al fondo hay sitio is a Peruvian TV series created in 2008-2009 by Efraín Aguilar. It deals with the problems of social differences and economic status. It's one of the most popular shows in Peru and is now being shown in Ecuador, Bolivia, Paraguay and Uruguay.",
    popularity: 1264.346,
    poster_path: '/g7cuCCkvoBuSwemTHYz3k0hvvmz.jpg',
    vote_average: 8.1,
    vote_count: 170,
  },
  {
    backdrop_path: '/o5GsA1G5YEruuUNOYvWjlArIC37.jpg',
    first_air_date: '2022-09-19',
    genre_ids: [10766],
    id: 210506,
    name: 'Sangue Oculto',
    origin_country: ['PT'],
    original_language: 'pt',
    original_name: 'Sangue Oculto',
    overview: '',
    popularity: 1262.089,
    poster_path: '/myCEG6C5Nk181jXzBek5MQEXpM2.jpg',
    vote_average: 5.1,
    vote_count: 8,
  },
  {
    backdrop_path: '/wdtM9fguzCuDVvpR1BvRw3AEmPG.jpg',
    first_air_date: '2022-10-11',
    genre_ids: [18, 80, 9648],
    id: 208249,
    name: 'Game of Witches',
    origin_country: ['KR'],
    original_language: 'ko',
    original_name: '마녀의 게임',
    overview:
      'Yu Kyung is a successful woman who is proficient enough to become an executive director of Chunha Group when she started as a secretary. She recently found out her daughter is alive, so she plans to get her back and take her revenge. Meanwhile, Hye Soo is a strong girl who faces challenges head-on. She has a daughter with Ji Ho, and she would do anything for her. However, she gets tragically betrayed by Ji Ho, the love of her life, over power and money. How will those two mothers end their fierce revenge?',
    popularity: 1253.421,
    poster_path: '/9bTjPzX48VZGalKEBI6tiknUyLI.jpg',
    vote_average: 2,
    vote_count: 1,
  },
  {
    backdrop_path: '/jLH03sLbkAGxrThdW6b2lrwwE4X.jpg',
    first_air_date: '2022-10-03',
    genre_ids: [18, 10751],
    id: 211239,
    name: 'The Love in Your Eyes',
    origin_country: ['KR'],
    original_language: 'ko',
    original_name: '내 눈에 콩깍지',
    overview:
      "Depicts the second love of a rogue daughter-in-law who appears in a 30-year-old gomtang restaurant, and a confident single mother Young Ih who says anything no matter what.\n\nJang Kyung Joon, who has the charm of a black-and-white man. Even though he shows the coolness of self-restraint from a large company that doesn't show his emotions easily, he shows both sides of being friendly in front of Lee Young Ih. Lee Young Ih, a single mother of steel mentality and a daughter-in-law with a bad attitude. She is sometimes angry, but she is a colorful charmer full of justice. Kim Hae Mi, her mother's daughter who has both her work and love in her hands, and Jang Kyung Joon's fiancée. It forms a tense rivalry with Bae Nouri. Jang Se Joon, the half-brother of Jang Kyung Joon, who has a friendly personality.",
    popularity: 1239.535,
    poster_path: '/gJnVJ3l4p1GDvGpwFedXhAJG3qE.jpg',
    vote_average: 4.5,
    vote_count: 4,
  },
  {
    backdrop_path: '/5gGfJIMB2ynRzERryQo8hTcdQXi.jpg',
    first_air_date: '2022-10-10',
    genre_ids: [18, 9648, 10751],
    id: 211174,
    name: 'Vengeance of the Bride',
    origin_country: ['KR'],
    original_language: 'ko',
    original_name: '태풍의 신부',
    overview:
      'The story of a woman who becomes the daughter-in-law of an enemy for desperate revenge.',
    popularity: 1231.49,
    poster_path: '/aHUyK2XA76mn9GM36wu2rRKvwB5.jpg',
    vote_average: 2,
    vote_count: 1,
  },
]
